---
- name: Install MariaDB
  hosts: all
  tasks:
    - name: install MariaDB Server
      ansible.builtin.dnf:
        name: mariadb-server
        state: latest
    - name: create wordpress.sql in root's home directory
      ansible.builtin.copy:
        src: wordpress.sql
        dest: /root/wordpress.sql
    - name: start MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: open port 3306
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled
        immediate: true
    - name: run a shell command to create the wordpress database
      ansible.builtin.shell:
        cmd: mysql < /root/wordpress.sql
        chdir: /root

