---
- name: Install MariaDB
  hosts: db
  tasks:
    - name: install MariaDB Server
      ansible.builtin.dnf:
        name: mariadb-server
        state: latest
    - name: start MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: open port 3306
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled
        immediate: true
