---
- name: Tear DB Environment Down
  hosts: all
  tasks:
    - name: remove MariaDB
      ansible.builtin.dnf:
        name: 
          - mariadb-server
        autoremove: true
        state: absent
    - name: remove firewall rules 3306
      ansible.builtin.firewalld:
        service: mysql
        state: disabled
        permanent: true
        immediate: true
